### ISSUE TITLE
Progress is outputted by stderr not stdout

### ISSUE THREAD

**Issue by shealan** [bbc/audiowaveform#129]
Using version 1.4

I can only seem to get the waveform progress by using this rather ugly code in node.

``` javascript
  const process = spawnSync('audiowaveform -i temp.mp3 -o output.json --pixels-per-second 20 --bits 8', {
    shell: true
  })

  process.stderr.on('data', data => {
    let match
    let buffer = data.toString()
    let regex = /^Done:\s+(.*)$/gm
    if ((match = regex.exec(buffer)) !== null) {
      console.log(match[1].replace('%', ''))
    }
  })
```

Does anyone know why this data only seems to come via `stderr` instead of `stdout` ?

**Comment by chrisn** [comment]
It's so that you can send the output JSON directly to stdout while keeping the status messages separate:

```
audiowaveform -i temp.mp3 --output-format json --pixels-per-second 20 --bits 8 > output.json
```

**Comment by leonroy** [comment]
We've just updated our version of `audiowaveform` from `1.3` to `1.6`and have been bitten by this change since we were using `stderr` to check for a failed run.

Is there anyway to revert the behaviour - ie. a flag?

For example if we run on a random file:
`audiowaveform -i NOT_AN_AUDIO_FILE.foo -o C0wpnzck36m_audioonly.dat -z 256 -b 8`

we get on `stderr`:
`Can't generate dat format output from Unknown file format`

If we run on an audio file:
`audiowaveform -i T0wpnzck36m_audioonly.wav -o T0wpnzck36m_audioonly.dat -z 256 -b 8`

we get on `stderr`:
```
Input file: T0wpnzck36m_audioonly.wav
Frames: 2930688
Sample rate: 48000 Hz
Channels: 1
Format: 0x10002
Sections: 1
Seekable: yes
Generating waveform data...
Samples per pixel: 256
Input channels: 1
Output channels: 1
Done: 100%
Read 2930688 frames
Generated 11448 points
Output file: T0wpnzck36m_audioonly.dat
Resolution: 8 bits
Channels: 1
Done
```

How are we supposed to tell if the command succeeds or not?

**Comment by chrisn** [comment]
This change was intentional, so that you can send the audiowaveform output to stdout. To check if the command succeeds, I recommend using the process exit status, which will be zero on success and non-zero on failure. If you don't need the information output you can use the `--quiet` option, then you'll only get the error message, if any.
