### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by ytmsuhsff** [bbc/audiowaveform#164]
Hello, I installed wavesurfer JS audio wave display, but the wave loading speed is very slow. You need to save the wave to the database to load the wave quickly. Is it possible to solve this problem.
(wavesurfer.js     https://wavesurfer-js.org/  )

Just like them
https://icons8.com/music/search/beach
https://tunetank.com/tracks/

This is my website
http://www.partymusic.cn/

我的邮件 304955091@qq.com

**Comment by ytmsuhsff** [comment]
Hello, how to use this plug-in? Can you help me, because I'm not a professional

**Comment by chrisn** [comment]
Thanks for your question. I can see your website takes a long time to load. This is because it's downloading all the MP3 audio files.

I'm not familiar with wavesurfer, but it may be possible to pre-calculate the waveform files on your web server, which avoids the need to download the full MP3 files.

You could possibly use audiowaveform to generate JSON or binary (.dat) format waveform files, host these files on your webserver, and then use this to show the waveform in the web page. Because the JSON or binary waveform files are much smaller than the MP3 files, your page should then be faster to load.

This is how we recommend people use our Peaks.js library (which is similar to wavesurver) - see our documentation [here](https://github.com/bbc/peaks.js#generating-waveform-data).

**Comment by ytmsuhsff** [comment]
I just think the same as you, because I'm not a professional and don't know much about this. I can send you the website program. Can you help me solve it? I can also pay if necessary

**Comment by chrisn** [comment]
To use audiowaveform, you'll need to install it on your server, there are some details [here](https://github.com/bbc/audiowaveform#installation).

There is information on how to use audiowaveform with wavesurfer [here](https://wavesurfer-js.org/faq/). You'll need to run audiowaveform on each MP3 file to produce a JSON file, then serve the JSON files from your website.

Then, in your JavaScript code, instead of passing the URL of the MP3 file to `wavesurver.load()`, you pass the URL of the waveform JSON file. It appears that you can use the `normalize: true` option in `WaveSurfer.create()` to use JSON files from audiowaveform.

**Comment by ytmsuhsff** [comment]
I have this template      https://zoomthe.me/soundportal/explore
After it uploads MP3, it can generate waves by itself  How does it do it  ，It does not need to be installed on the server
After this template is installed, you can generate waves as long as you upload MP3, and then save them to the database，Opening it again is very fast

**Comment by ytmsuhsff** [comment]
有没有办法做到这一点

**Comment by ytmsuhsff** [comment]
Is there any way to do the same as it

**Comment by jmcoder1** [comment]
> Is there any way to do the same as it

Did you figure out how to use audiowaveform in your JS code ?

**Comment by chrisn** [comment]
I'll close this, but please re-open or raise a new issue if you still need help.
