### ISSUE TITLE
Enhancement request: json to png?

### ISSUE THREAD

**Issue by mbordash** [bbc/audiowaveform#18]
How about an option to convert previously generated json data to png?

**Comment by chrisn** [comment]
By design, the canonical data format is the [binary .dat format](https://github.com/bbc/audiowaveform/blob/master/doc/DataFormat.md), and the JSON format was only intended for browsers lacking ArrayBuffer support for dealing with binary data. That said, I'm not entirely against enabling audiowaveform to read JSON files.

**Comment by chrisn** [comment]
I have added JSON support in https://github.com/bbc/audiowaveform/commit/dccc7ade7f20f63f161e4c1ab700605234e843d2.
