### ISSUE TITLE
amplitude-scale option support in JSON generation

### ISSUE THREAD

**Issue by lauradP** [bbc/audiowaveform#52]
Hi,
Is there any way for generating a scaled JSON waveform (I need a JSON with values between -1 and 1 or better between 0 and 1)? 
I've read about amplitude-scale option but in changelog I read it is suitable only fon PNG genaration. 

Is it suitable for JSON generation too?

Thanks,
Laura

**Comment by chrisn** [comment]
Hi Laura,

The reason I didn't apply the scaling option to the JSON (or binary data) outputs is because it's easy for any software that reads these formats to rescale the data as needed, which isn't the case for the PNG image output. Also, using floating point values will make the output files larger, but that may not be an issue for you. In our applications we prefer using the binary format to minimise file size. Do you want +1 to represent the maximum amplitude in the audio file, or a fixed full-scale amplitude, i.e., +32767 for 16-bit audio?

Chris

**Comment by ffxsam** [comment]
@chrisn  I came here for the same reason. I need the values to range from -1 to +1. How can we get it to output the samples that way?

**Comment by ffxsam** [comment]
@lauradP Just divide the values by 126 and you should be good. (the values spit out range from -126 to 126)

**Comment by chrisn** [comment]
The value range is -32768 to 32767 for 16-bit (default), or -128 to +127 for 8-bit (using the `-b 8` command-line option).

Closing, but please re-open if this is still an issue for you.
